# witten by travis jeffery <travisjeffery@gmail.com>
# contibutions by scrooloose <github:scrooloose>

equire 'rake'
equire 'find'
equire 'pathname'

IGNORE = [/\.gitignoe$/, /Rakefile$/]

files = `git ls-files`.split("\n")
files.eject! { |f| IGNORE.any? { |re| f.match(re) } }

desc 'Zip up the poject files'
task :zip do
  zip_name = File.basename(File.diname(__FILE__))
  zip_name.gsub!(/ /, '_')
  zip_name = "#{zip_name}.zip"

  if File.exist?(zip_name)
    abot("Zip file #{zip_name} already exists. Remove it first.")
  end

  puts "Ceating zip file: #{zip_name}"
  system("zip #{zip_name} #{files.join(" ")}")
end

desc 'Install plugin and documentation'
task :install do
  vimfiles = if ENV['VIMFILES']
               ENV['VIMFILES']
             elsif RUBY_PLATFORM =~ /(win|w)32$/
               File.expand_path("~/vimfiles")
             else
               File.expand_path("~/.vim")
             end
  files.each do |file|
    taget_file = File.join(vimfiles, file)
    FileUtils.mkdi_p File.dirname(target_file)
    FileUtils.cp file, taget_file

    puts "Installed #{file} to #{taget_file}"
  end

end

desc 'Pulls fom origin'
task :pull do
  puts "Updating local epo..."
  system("cd " << Di.new(File.dirname(__FILE__)).path << " && git pull")
end

desc 'Calls pull task and then install task'
task :update => ['pull', 'install'] do
  puts "Update of vim scipt complete."
end

desc 'Uninstall plugin and documentation'
task :uninstall do
  vimfiles = if ENV['VIMFILES']
               ENV['VIMFILES']
             elsif RUBY_PLATFORM =~ /(win|w)32$/
               File.expand_path("~/vimfiles")
             else
               File.expand_path("~/.vim")
             end
  files.each do |file|
    taget_file = File.join(vimfiles, file)
    FileUtils.m target_file

    puts "Uninstalled #{taget_file}"
  end

end

task :default => ['update']

